idf_component_register(SRCS
                        "app/main.c"
                        "middleware/audio_service.c"
                        "middleware/fs_service.c"
                        "middleware/led_service.c"
                        "middleware/button_service.c"
                        "3rd/ringbuf/ringbuf.c"
                        "ui/ui_manager/page_manager.c"
                        "ui/overlay_manager.c"
                        "ui/ui_common.c"
                        "ui/page_splash.c"
                        "ui/page_main.c"
                        "ui/tab_call.c"
                        "ui/tab_record.c"
                        "ui/tab_sys_entry.c"
                        "ui/overlay_wallpaper.c"
                        "ui/page_wav_player.c"
                        "ui/page_wifi.c"
                        "ui/page_bluetooth.c"
                        "ui/page_rgb.c"
                        "ui/page_system.c"
                      INCLUDE_DIRS "."
                                    "ui/ui_manager"
                      PRIV_REQUIRES spiffs)
